In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/Excel.csv')

In [ ]:
print(df)

    ROLLNO  AGE GENDER BRANCH SECTION
0      101   19      M    CSE       A
1      102   20      M   AIML       B
2      103   21      F     DS       C
3      104   22      F     ME       D
4      105   19      F    CSE       F
5      106   22      M    CSE       E
6      107   23      M   AIML       A
7      108   20      M   AIML       D
8      109   20      F     DS       B
9      110   18      M     ME       A
10     111   19      F     ME       A
11     112   24      M    CSE       C
12     113   25      M   AIML       A
13     114   25      F     ME       C

In [ ]:
print(df.head())

   ROLLNO  AGE GENDER BRANCH SECTION
0     101   19      M    CSE       A
1     102   20      M   AIML       B
2     103   21      F     DS       C
3     104   22      F     ME       D
4     105   19      F    CSE       F

In [ ]:
print(df.tail())

    ROLLNO  AGE GENDER BRANCH SECTION
9      110   18      M     ME       A
10     111   19      F     ME       A
11     112   24      M    CSE       C
12     113   25      M   AIML       A
13     114   25      F     ME       C

In [ ]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   ROLLNO   14 non-null     int64
 1   AGE      14 non-null     int64
 2   GENDER   14 non-null     object
 3   BRANCH   14 non-null     object
 4   SECTION  14 non-null     object
dtypes: int64(2), object(3)
memory usage: 692.0+ bytes
None

In [ ]:
df.describe()

         ROLLNO        AGE
count   14.0000  14.000000
mean   107.5000  21.214286
std      4.1833   2.326389
min    101.0000  18.000000
25%    104.2500  19.250000
50%    107.5000  20.500000
75%    110.7500  22.750000
max    114.0000  25.000000

In [ ]:
df.shape

(14, 5)

In [ ]:
df.columns

Index(['ROLLNO', 'AGE', 'GENDER', 'BRANCH', 'SECTION'], dtype='object')

In [ ]:
df.dtypes

ROLLNO      int64
AGE         int64
GENDER     object
BRANCH     object
SECTION    object
dtype: object

In [ ]:
df.isnull()

    ROLLNO    AGE  GENDER  BRANCH  SECTION
0    False  False   False   False    False
1    False  False   False   False    False
2    False  False   False   False    False
3    False  False   False   False    False
4    False  False   False   False    False
5    False  False   False   False    False
6    False  False   False   False    False
7    False  False   False   False    False
8    False  False   False   False    False
9    False  False   False   False    False
10   False  False   False   False    False
11   False  False   False   False    False
12   False  False   False   False    False
13   False  False   False   False    False

In [ ]:
df.dtypes

ROLLNO      int64
AGE         int64
GENDER     object
BRANCH     object
SECTION    object
dtype: object

In [ ]:
df.isnull().sum()

ROLLNO     0
AGE        0
GENDER     0
BRANCH     0
SECTION    0
dtype: int64

In [ ]:
df.loc(0)

In [ ]:
df.iloc[0]

ROLLNO     101
AGE         19
GENDER       M
BRANCH     CSE
SECTION      A
Name: 0, dtype: object

In [ ]:
df.loc(1)

In [ ]:
ages=df['AGE']
print(ages)

0     19
1     20
2     21
3     22
4     19
5     22
6     23
7     20
8     20
9     18
10    19
11    24
12    25
13    25
Name: AGE, dtype: int64

In [ ]:
adults = df[(df['AGE'] >=19) & (df['AGE'] <= 20)]
print("Those whose age is between 19 and 20:\n", adults)

Those whose age is between 19 and 20:
     ROLLNO  AGE GENDER BRANCH SECTION
0      101   19      M    CSE       A
1      102   20      M   AIML       B
4      105   19      F    CSE       F
7      108   20      M   AIML       D
8      109   20      F     DS       B
10     111   19      F     ME       A

In [ ]:
male=df['GENDER']

In [ ]:
age=df[df["AGE"] > 20]
print(age)

    ROLLNO  AGE GENDER BRANCH SECTION
2      103   21      F     DS       C
3      104   22      F     ME       D
5      106   22      M    CSE       E
6      107   23      M   AIML       A
11     112   24      M    CSE       C
12     113   25      M   AIML       A
13     114   25      F     ME       C

In [ ]:
males = df[df['GENDER'] == 'M']
print("Male candidates:\n", males)

Male candidates:
     ROLLNO  AGE GENDER BRANCH SECTION
0      101   19      M    CSE       A
1      102   20      M   AIML       B
5      106   22      M    CSE       E
6      107   23      M   AIML       A
7      108   20      M   AIML       D
9      110   18      M     ME       A
11     112   24      M    CSE       C
12     113   25      M   AIML       A

In [ ]:
print("Age in ascending order:")
df.sort_values(by='AGE', ascending=True)

Age in ascending order:

    ROLLNO  AGE GENDER BRANCH SECTION
9      110   18      M     ME       A
0      101   19      M    CSE       A
10     111   19      F     ME       A
4      105   19      F    CSE       F
7      108   20      M   AIML       D
8      109   20      F     DS       B
1      102   20      M   AIML       B
2      103   21      F     DS       C
3      104   22      F     ME       D
5      106   22      M    CSE       E
6      107   23      M   AIML       A
11     112   24      M    CSE       C
12     113   25      M   AIML       A
13     114   25      F     ME       C